'use client';

import { useMemo, useState } from 'react';

const Icon = ({ name, size = 20, stroke = 1.8 }) => {
  const common = { width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:stroke,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true };
  const paths = {
    home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>, folder:<path d="M3 6h6l2 2h10v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z"/>,
    file:<><path d="M6 2h9l5 5v15H6z"/><path d="M14 2v6h6"/><path d="M9 13h6M9 17h6"/></>, alert:<><circle cx="12" cy="12" r="9"/><path d="M12 8v5M12 16h.01"/></>,
    scale:<><path d="M12 3v18M5 7h14M7 7l-4 7h8zM17 7l-4 7h8z"/></>, chart:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>,
    settings:<><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-1.9-2.1-2.1-1.9.9-1.7-.7L10.5 2h-3l-.7 2-1.7.7-1.9-.9-2.1 2.1.9 1.9-.7 1.7-2 .7v3l2 .7.7 1.7-.9 1.9 2.1 2.1 1.9-.9 1.7.7.7 2h3l.7-2 1.7-.7 1.9.9 2.1-2.1-.9-1.9.7-1.7z"/></>,
    plus:<path d="M12 5v14M5 12h14"/>, bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>, chevron:<path d="m9 10 3 3 3-3"/>,
    upload:<><path d="M12 16V4M7 9l5-5 5 5"/><path d="M5 20h14"/></>, search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    dollar:<><circle cx="12" cy="12" r="9"/><path d="M15 8.5c-.7-.8-1.7-1.2-3-1.2-1.8 0-3 .9-3 2.3 0 3.4 6 1.6 6 5 0 1.4-1.2 2.4-3.2 2.4-1.4 0-2.5-.5-3.3-1.4M12 5v14"/></>,
    whatsapp:<><path d="M20.5 11.8a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.3-4.7a8.5 8.5 0 1 1 16.2-4Z"/><path d="M8.7 8.2c.3 2.5 2.3 4.6 4.8 5.1"/></>,
    download:<><path d="M12 3v12M7 10l5 5 5-5"/><path d="M4 21h16"/></>, copy:<><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></>,
    filter:<path d="M3 5h18l-7 8v6l-4 2v-8Z"/>, eye:<><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></>,
    check:<path d="m5 12 4 4L19 6"/>, x:<path d="M6 6l12 12M18 6 6 18"/>, user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, lock:<><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, credit:<><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/></>
  };
  return <svg {...common}>{paths[name]}</svg>;
};

function Logo(){return <div className="logo"><svg className="logo-mark" viewBox="0 0 72 72"><path d="M15 61V37h10v24H15Zm14 0V28h10v33H29Zm14 0V18h10v43H43Z"/><path d="M13 12h31c11 0 18 6 18 16 0 8-5 13-12 15l12 17H48L37 44h-8V32h14c5 0 8-2 8-6s-3-6-8-6H25v9L10 16 25 3v9H13Z"/></svg><div className="logo-word"><span>Recupera</span><b>Glosa</b></div></div>}

const nav=[['home','Visão geral'],['folder','Lotes'],['file','Guias'],['alert','Glosas'],['scale','Recursos'],['chart','Relatórios'],['settings','Configurações']];
const lotes=[
  {arquivo:'demonstrativo_0425.xml',data:'12/05/2025 14:32',operadora:'Unimed',guias:78,glosas:12,valor:'R$ 4.350,20',status:'Processado'},
  {arquivo:'demonstrativo_0325.xml',data:'08/05/2025 09:15',operadora:'Amil',guias:65,glosas:9,valor:'R$ 2.180,50',status:'Processado'},
  {arquivo:'demonstrativo_0225.xml',data:'02/05/2025 16:48',operadora:'SulAmérica',guias:43,glosas:6,valor:'R$ 1.920,30',status:'Processado'},
  {arquivo:'demonstrativo_0125.xml',data:'28/04/2025 11:20',operadora:'Bradesco',guias:52,glosas:8,valor:'R$ 3.120,40',status:'Processado'},
  {arquivo:'demonstrativo_1224.xml',data:'15/04/2025 08:55',operadora:'Unimed',guias:91,glosas:7,valor:'R$ 2.860,15',status:'Processado'}
];
const guias=[
  ['00038492','Maria de Souza','Unimed','Consulta','R$ 380,00','R$ 300,00','R$ 80,00'],['00038475','Carlos Almeida','Amil','Procedimento','R$ 1.240,00','R$ 800,00','R$ 440,00'],['00038440','Ana Costa','SulAmérica','Exame','R$ 720,00','R$ 540,00','R$ 180,00'],['00038398','João Pereira','Bradesco','Consulta','R$ 450,00','R$ 350,00','R$ 100,00'],['00038364','Patrícia Lima','Unimed','Cirurgia','R$ 3.800,00','R$ 2.600,00','R$ 1.200,00']
];
const glosas=[
  ['00038492','1019','Procedimento não coberto','R$ 80,00','Alta','Recorrível'],['00038475','1302','Código incorreto','R$ 440,00','Alta','Recorrível'],['00038440','1701','Documentação insuficiente','R$ 180,00','Média','Recorrível'],['00038398','1008','Prazo de envio expirado','R$ 100,00','Baixa','Analisar'],['00038364','1405','Valor acima da tabela','R$ 1.200,00','Alta','Recorrível']
];
const recursos=[
  ['REC-0425-012','Guia 00038492','Procedimento não coberto','R$ 80,00','Pronto'],['REC-0425-009','Guia 00038475','Código incorreto','R$ 440,00','Pronto'],['REC-0325-006','Guia 00038440','Documentação insuficiente','R$ 180,00','Enviado'],['REC-0325-002','Guia 00038398','Prazo de envio expirado','R$ 100,00','Rascunho']
];

export default function Page(){
 const [tab,setTab]=useState('Visão geral'); const [upload,setUpload]=useState(false); const [query,setQuery]=useState('');
 const title=tab; const sub={
  'Visão geral':'Acompanhe suas auditorias e valores recuperáveis','Lotes':'Gerencie os demonstrativos enviados para auditoria','Guias':'Consulte todas as guias identificadas nos demonstrativos','Glosas':'Priorize valores glosados e oportunidades de recuperação','Recursos':'Revise, copie e envie contestações prontas','Relatórios':'Entenda a evolução financeira e os principais motivos','Configurações':'Gerencie clínica, equipe, cobrança e segurança'
 }[tab];
 return <main className="app-shell full-app">
  <header className="topbar"><Logo/><div className="top-actions"><button className="icon-button"><Icon name="bell"/></button><button className="clinic"><span>C</span>Clínica Sorriso<Icon name="chevron" size={16}/></button></div></header>
  <div className="app-body"><aside className="sidebar"><nav>{nav.map(([icon,label])=><button onClick={()=>setTab(label)} className={tab===label?'active':''} key={label}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="plan-card"><strong>Plano Profissional</strong><p>Próxima cobrança<br/><b>12/06/2025</b></p><button>Gerenciar plano</button></div></aside>
  <section className="content"><div className="content-head"><div><h1>{title}</h1><p>{sub}</p></div>{tab!=='Configurações'&&<button className="primary" onClick={()=>setUpload(true)}><Icon name="plus"/>Novo upload</button>}</div>
   {tab==='Visão geral'&&<Overview setTab={setTab}/>} {tab==='Lotes'&&<Lotes query={query} setQuery={setQuery}/>} {tab==='Guias'&&<Guias/>} {tab==='Glosas'&&<Glosas/>} {tab==='Recursos'&&<Recursos/>} {tab==='Relatórios'&&<Relatorios/>} {tab==='Configurações'&&<Configuracoes/>}
  </section></div>{upload&&<UploadModal close={()=>setUpload(false)}/>}</main>
}

function Overview({setTab}){return <div className="dashboard-grid"><div className="kpi recoverable"><p>Valor recuperável</p><strong>R$ 18.430,75</strong><small>em 42 glosas</small><Spark/></div><Kpi title="Lotes processados" value="15" sub="últimos 30 dias" icon="file" tone="green"/><Kpi title="Guias auditadas" value="342" sub="últimos 30 dias" icon="file" tone="blue"/><div className="reasons card"><h2>Motivos mais recorrentes</h2><div className="reason-content"><Donut/><div className="legend"><Legend c="green" t="Procedimento não coberto" v="35%"/><Legend c="teal" t="Código incorreto" v="28%"/><Legend c="orange" t="Documentação insuficiente" v="18%"/><Legend c="slate" t="Outros" v="19%"/></div></div><button className="outline" onClick={()=>setTab('Relatórios')}>Ver relatório completo</button></div><div className="lots card"><h2>Últimos lotes</h2><SimpleTable heads={['Arquivo','Enviado em','Guias','Glosas','Valor recuperável','Status']} rows={lotes.slice(0,3).map(x=>[x.arquivo,x.data,x.guias,x.glosas,x.valor,<Status key={x.arquivo} text={x.status}/>])}/><button className="outline small" onClick={()=>setTab('Lotes')}>Ver todos os lotes</button></div><div className="help card"><h2>Precisa de ajuda?</h2><p>Fale com nosso time e tire suas dúvidas.</p><button className="outline whatsapp"><Icon name="whatsapp"/>Falar no WhatsApp</button></div></div>}

function Lotes({query,setQuery}){const filtered=useMemo(()=>lotes.filter(x=>x.arquivo.toLowerCase().includes(query.toLowerCase())||x.operadora.toLowerCase().includes(query.toLowerCase())),[query]);return <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar arquivo ou operadora..."/><div className="metric-row"><Metric label="Total de lotes" value="15"/><Metric label="Processados" value="14" positive/><Metric label="Em processamento" value="1"/><Metric label="Valor identificado" value="R$ 18.430,75" positive/></div><div className="page-card"><div className="card-title"><div><h2>Todos os lotes</h2><p>Demonstrativos XML enviados para análise</p></div><button className="outline compact"><Icon name="download"/>Exportar</button></div><DataTable heads={['Arquivo','Operadora','Enviado em','Guias','Glosas','Valor recuperável','Status','']} rows={filtered.map(x=>[<span className="with-icon" key="a"><Icon name="file" size={17}/>{x.arquivo}</span>,x.operadora,x.data,x.guias,x.glosas,<b className="money">{x.valor}</b>,<Status key="s" text={x.status}/>,<button className="row-action" key="r"><Icon name="eye" size={17}/></button>])}/></div></>}
function Guias(){return <><Toolbar placeholder="Buscar guia, paciente ou operadora..."/><div className="metric-row"><Metric label="Guias auditadas" value="342"/><Metric label="Com glosa" value="42" warn/><Metric label="Sem glosa" value="300" positive/><Metric label="Taxa de aprovação" value="87,7%" positive/></div><div className="page-card"><div className="card-title"><div><h2>Guias auditadas</h2><p>Valores apresentados, pagos e glosados</p></div><button className="outline compact"><Icon name="download"/>Exportar</button></div><DataTable heads={['Nº da guia','Paciente','Operadora','Tipo','Apresentado','Pago','Glosado','']} rows={guias.map(r=>[r[0],r[1],r[2],r[3],r[4],r[5],<b className="orange-text" key="g">{r[6]}</b>,<button className="row-action" key="a"><Icon name="eye" size={17}/></button>])}/></div></>}
function Glosas(){return <><div className="metric-row"><Metric label="Total glosado" value="R$ 18.430,75" warn/><Metric label="Recorrível" value="R$ 15.285,40" positive/><Metric label="Em análise" value="R$ 2.045,35"/><Metric label="Não recorrível" value="R$ 1.100,00"/></div><div className="split-layout"><div className="page-card"><div className="card-title"><div><h2>Glosas identificadas</h2><p>Ordenadas por potencial de recuperação</p></div><button className="outline compact"><Icon name="filter"/>Filtrar</button></div><DataTable heads={['Guia','Código','Motivo','Valor','Prioridade','Situação']} rows={glosas.map(r=>[r[0],r[1],r[2],<b className="orange-text" key="v">{r[3]}</b>,<Priority key="p" text={r[4]}/>,<Status key="s" text={r[5]}/>])}/></div><aside className="insight-card"><span className="insight-icon"><Icon name="dollar"/></span><h3>Maior oportunidade</h3><strong>R$ 6.450,20</strong><p>35% do valor recuperável vem de procedimentos classificados como “não cobertos”.</p><button className="primary full">Criar recursos</button></aside></div></>}
function Recursos(){return <><div className="metric-row"><Metric label="Recursos prontos" value="18" positive/><Metric label="Enviados" value="12"/><Metric label="Aceitos" value="8" positive/><Metric label="Taxa de sucesso" value="66,7%" positive/></div><div className="page-card"><div className="card-title"><div><h2>Recursos de glosa</h2><p>Textos gerados automaticamente para contestação</p></div><button className="outline compact"><Icon name="download"/>Baixar todos</button></div><DataTable heads={['Recurso','Referência','Motivo','Valor','Status','Ações']} rows={recursos.map(r=>[r[0],r[1],r[2],<b className="money" key="m">{r[3]}</b>,<Status key="s" text={r[4]}/>,<div className="action-pair" key="a"><button className="row-action"><Icon name="eye" size={17}/></button><button className="row-action"><Icon name="copy" size={17}/></button><button className="row-action"><Icon name="download" size={17}/></button></div>])}/></div><div className="resource-preview"><div><span className="eyebrow">PRÉVIA DO RECURSO</span><h3>Contestação — código 1019</h3><p>Prezados, solicitamos a reanálise da glosa aplicada à guia nº 00038492. O procedimento foi realizado conforme indicação clínica e encontra-se coberto pelas condições contratuais vigentes...</p></div><button className="primary"><Icon name="copy"/>Copiar texto</button></div></>}
function Relatorios(){return <><div className="report-head"><div className="segmented"><button className="active">Últimos 30 dias</button><button>3 meses</button><button>12 meses</button></div><button className="outline compact"><Icon name="download"/>Exportar PDF</button></div><div className="metric-row"><Metric label="Valor apresentado" value="R$ 98.765,40"/><Metric label="Valor pago" value="R$ 80.334,65"/><Metric label="Valor glosado" value="R$ 18.430,75" warn/><Metric label="Recuperado" value="R$ 9.820,30" positive/></div><div className="report-grid"><div className="page-card chart-card"><div className="card-title"><div><h2>Evolução do valor recuperável</h2><p>Comparativo mensal dos últimos 6 meses</p></div></div><BarChart/></div><div className="page-card"><div className="card-title"><div><h2>Motivos de glosa</h2><p>Participação no valor total</p></div></div><div className="large-donut"><Donut/><div><Legend c="green" t="Procedimento não coberto" v="35%"/><Legend c="teal" t="Código incorreto" v="28%"/><Legend c="orange" t="Documentação insuficiente" v="18%"/><Legend c="slate" t="Outros" v="19%"/></div></div></div></div></>}
function Configuracoes(){const [section,setSection]=useState('Clínica');return <div className="settings-layout"><aside className="settings-nav">{[['user','Clínica'],['user','Equipe'],['credit','Assinatura'],['bell','Notificações'],['lock','Segurança']].map(([i,l])=><button className={section===l?'active':''} onClick={()=>setSection(l)} key={l}><Icon name={i}/>{l}</button>)}</aside><div className="page-card settings-card"><h2>{section}</h2><p className="settings-sub">Atualize as informações e preferências desta seção.</p>{section==='Clínica'&&<FormClinic/>}{section==='Equipe'&&<Team/>}{section==='Assinatura'&&<Billing/>}{section==='Notificações'&&<Notifications/>}{section==='Segurança'&&<Security/>}</div></div>}

function FormClinic(){return <form className="form-grid"><Field label="Nome da clínica" value="Clínica Sorriso"/><Field label="CNPJ" value="12.345.678/0001-90"/><Field label="E-mail financeiro" value="financeiro@clinicasorriso.com.br"/><Field label="Telefone" value="(11) 99999-0000"/><Field label="CNES" value="1234567"/><Field label="Cidade" value="São Paulo — SP"/><div className="form-actions"><button type="button" className="primary">Salvar alterações</button></div></form>}
function Team(){return <div><div className="team-row"><div className="avatar">HC</div><div><b>Henrique Costa</b><p>henrique@clinicasorriso.com.br</p></div><Status text="Administrador"/></div><div className="team-row"><div className="avatar">MS</div><div><b>Mariana Souza</b><p>mariana@clinicasorriso.com.br</p></div><Status text="Membro"/></div><button className="primary"><Icon name="plus"/>Convidar membro</button></div>}
function Billing(){return <div className="billing"><div className="billing-plan"><div><span className="eyebrow">PLANO ATUAL</span><h3>Profissional</h3><p>Auditorias ilimitadas e geração automática de recursos.</p></div><strong>R$ 197<small>/mês</small></strong></div><div className="billing-note"><Icon name="credit"/><div><b>Próxima cobrança em 12/06/2025</b><p>Cartão final 4242</p></div><button className="outline compact">Alterar cartão</button></div></div>}
function Notifications(){return <div className="toggle-list"><Toggle title="Auditoria concluída" sub="Receba um aviso quando um lote terminar de processar."/><Toggle title="Novo valor recuperável" sub="Aviso quando forem encontradas novas glosas recorríveis."/><Toggle title="Resumo semanal" sub="Receba toda segunda-feira um resumo financeiro."/></div>}
function Security(){return <div className="security"><div className="security-item"><Icon name="lock"/><div><b>Link mágico por e-mail</b><p>Seu acesso está protegido sem necessidade de senha.</p></div><Status text="Ativo"/></div><button className="outline compact">Encerrar outras sessões</button></div>}

function UploadModal({close}){return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-x" onClick={close}><Icon name="x"/></button><span className="upload-symbol"><Icon name="upload" size={30}/></span><h2>Enviar demonstrativo</h2><p>Selecione um arquivo XML no padrão TISS para iniciar a auditoria.</p><label className="dropzone"><Icon name="upload" size={28}/><b>Arraste o XML para cá</b><span>ou clique para selecionar o arquivo</span><input type="file" accept=".xml"/></label><div className="modal-actions"><button className="outline" onClick={close}>Cancelar</button><button className="primary">Analisar arquivo</button></div></div></div>}
function Toolbar({query='',setQuery=()=>{},placeholder}){return <div className="toolbar"><label><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label><button className="outline compact"><Icon name="filter"/>Filtros</button></div>}
function Metric({label,value,positive,warn}){return <div className="metric-card"><p>{label}</p><strong className={positive?'positive':warn?'warn':''}>{value}</strong><small>últimos 30 dias</small></div>}
function Kpi({title,value,sub,icon,tone}){return <div className="kpi"><p>{title}</p><strong className="dark">{value}</strong><small>{sub}</small><span className={`kpi-icon ${tone}`}><Icon name={icon}/></span></div>}
function Spark(){return <svg viewBox="0 0 200 76" className="spark"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#16A34A" stopOpacity=".24"/><stop offset="1" stopColor="#16A34A" stopOpacity="0"/></linearGradient></defs><path className="area" d="M4 63 L18 57 L30 59 L43 48 L56 52 L69 43 L82 46 L94 36 L106 39 L118 30 L130 34 L143 22 L156 25 L169 13 L184 17 L196 5 L196 75 L4 75Z"/><path d="M4 63 L18 57 L30 59 L43 48 L56 52 L69 43 L82 46 L94 36 L106 39 L118 30 L130 34 L143 22 L156 25 L169 13 L184 17 L196 5"/><circle cx="196" cy="5" r="4"/></svg>}
function Donut(){return <div className="donut"><div/></div>}
function Legend({c,t,v}){return <div className="legend-row"><span className={`dot ${c}`}/><p>{t}</p><b>{v}</b></div>}
function Status({text}){const cls=text.toLowerCase().replaceAll(' ','-').normalize('NFD').replace(/[\u0300-\u036f]/g,'');return <em className={`status ${cls}`}>{text}</em>}
function Priority({text}){return <span className={`priority ${text.toLowerCase()}`}>{text}</span>}
function SimpleTable({heads,rows}){return <div className="simple-table"><div className="simple-row head">{heads.map(h=><span key={h}>{h}</span>)}</div>{rows.map((r,i)=><div className="simple-row" key={i}>{r.map((v,j)=><span key={j}>{v}</span>)}</div>)}</div>}
function DataTable({heads,rows}){return <div className="data-table-wrap"><table className="data-table"><thead><tr>{heads.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function BarChart(){const vals=[42,58,49,76,68,91];return <div className="bar-chart">{vals.map((v,i)=><div className="bar-col" key={i}><span className="bar-value">R$ {v/10}k</span><div className="bar" style={{height:`${v}%`}}/><small>{['Dez','Jan','Fev','Mar','Abr','Mai'][i]}</small></div>)}</div>}
function Field({label,value}){return <label className="field"><span>{label}</span><input defaultValue={value}/></label>}
function Toggle({title,sub}){const [on,setOn]=useState(true);return <div className="toggle-row"><div><b>{title}</b><p>{sub}</p></div><button onClick={()=>setOn(!on)} className={`toggle ${on?'on':''}`}><span/></button></div>}
